name: Deploy Node.js App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Gantikan dengan versi Node.js yang anda gunakan

      - name: Install dependencies
        run: npm install

      - name: Run application
        run: npm start &
        env:
          PORT: ${{ secrets.PORT }} # Gantikan dengan variabel environment jika perlu
